# Generated by Django 4.2.17 on 2025-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_alter_user_options_alter_user_managers_and_more'),
        ('profiles', '0002_user_quizzes_completed_user_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
