# Generated by Django 5.2.1 on 2025-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
