# Generated by Django 5.2.1 on 2025-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquizsession_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback_if_correct',
            field=models.TextField(blank=True, help_text='Feedback shown when this answer is correct', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='feedback_if_wrong',
            field=models.TextField(blank=True, help_text='Feedback shown when this answer is selected but is incorrect', null=True),
        ),
    ]
