# Generated by Django 5.2.1 on 2025-06-01 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='match_pair',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Single Choice'), ('MULTI', 'Multiple Select'), ('TEXT', 'Free Text'), ('BLANK', 'Fill in the Blanks'), ('BOOL', 'True/False'), ('ORDER', 'Arrange in Order'), ('MATCH', 'Match the Following')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
