# Generated by Django 5.2.1 on 2025-06-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_feedback_if_correct_answer_feedback_if_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Single Choice'), ('MULTI', 'Multiple Select'), ('TEXT', 'Free Text'), ('ORDER', 'Arrange in Order'), ('MATCH', 'Match the Following')], max_length=10),
        ),
    ]
