# Generated by Django 4.2.17 on 2025-06-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboardentry',
            old_name='total_points',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='criteria',
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.CreateModel(
            name='BadgeCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('total_score', 'Total Score'), ('quizzes_completed', 'Quizzes Completed')], max_length=50)),
                ('operator', models.CharField(choices=[('>=', '≥'), ('==', '='), ('<', '<'), ('>', '>')], max_length=5)),
                ('value', models.IntegerField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='gamification.badge')),
            ],
        ),
    ]
